### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by NotAShelf** [thinkingsand/rat#15]
Hey! I'm packaging this program for Nix, but I've noticed that it's got no active license - which would put it under the unfree category and throw a very annoying warning for those trying to use it without unfree packages enabled on their system. Any chance we could get an official license?

**Comment by IAGOnGithub** [comment]
Oh shit hello raf

**Comment by NotAShelf** [comment]
hi

**Comment by thinkingsand** [comment]
Hi. Sorry about that, I think it was GPL at one point but the license file was removed by mistake when I switched over to the new code. I'll just Unlicense it to make things easier.

**Comment by thinkingsand** [comment]
fixed in 5639d3cbeae406d3e320cfb17f971af64a733b4f

**Comment by NotAShelf** [comment]
appreciated
