### ISSUE TITLE
No fedora release?

### ISSUE THREAD

**Issue by nexy7574** [thinkingsand/rat#18]
Hello! Why is there no fedora RPM? I would like to install this program on my fedora computer

thank you rat
happy ratting

**Comment by IAGOnGithub** [comment]
You can pretty easily build it using the makefile. I don't believe it has any required dependencies aside from a C compiler.

**Comment by nexy7574** [comment]
ngl I just think it'd be funny to have debs and RPMs with pre-built packages. It won't be difficult, afaik github has their own registry for apt/dnf

**Comment by nexy7574** [comment]
see: #19

**Comment by nexy7574** [comment]
Fixed!
